Repository aicoe-aiops/mailing-list-analysis-toolkit, pull requests merged in 2021-04, with the labels that each got.

#66 add sentiment_analysis.ipynb
  Pipfile
  Pipfile.lock
  notebooks/02_analyses/sentiment_analysis.ipynb
Labels: approved, size/XXL

#69 regex cleaning refactored in `raw_to_text.ipynb`
  notebooks/01_collect_data/raw_to_text.ipynb
Labels: approved, size/L

#54 Hatesonar Analysis Notebook
  notebooks/stage/hatesonar_analysis.ipynb
Labels: approved, do-not-merge/hold, lgtm, size/XXL
